package uade.fain.ia.tpo.interfaces.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2014-11-08T16:36:54.715-03:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = "http://soap.interfaces.tpo.ia.fain.uade/", name = "OrdenDespachoSoapWS")
@XmlSeeAlso({ObjectFactory.class})
public interface OrdenDespachoSoapWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "recibirOrdenDespacho", targetNamespace = "http://soap.interfaces.tpo.ia.fain.uade/", className = "uade.fain.ia.tpo.interfaces.soap.RecibirOrdenDespacho")
    @WebMethod
    @ResponseWrapper(localName = "recibirOrdenDespachoResponse", targetNamespace = "http://soap.interfaces.tpo.ia.fain.uade/", className = "uade.fain.ia.tpo.interfaces.soap.RecibirOrdenDespachoResponse")
    public uade.fain.ia.tpo.interfaces.soap.Resultado recibirOrdenDespacho(
        @WebParam(name = "arg0", targetNamespace = "")
        uade.fain.ia.tpo.interfaces.soap.OrdenDespacho arg0
    ) throws OrdenDespachoYaExisteExceptionException, ArticuloDesconocidoExceptionException, ExceptionException;
}
