package webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2014-11-08T12:05:08.131-03:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = "http://webservices/", name = "WSMonitoreo")
@XmlSeeAlso({ObjectFactory.class})
public interface WSMonitoreo {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registrarVenta", targetNamespace = "http://webservices/", className = "webservices.RegistrarVenta")
    @WebMethod
    @ResponseWrapper(localName = "registrarVentaResponse", targetNamespace = "http://webservices/", className = "webservices.RegistrarVentaResponse")
    public java.lang.String registrarVenta(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "enviarInformeAuditoria", targetNamespace = "http://webservices/", className = "webservices.EnviarInformeAuditoria")
    @WebMethod
    @ResponseWrapper(localName = "enviarInformeAuditoriaResponse", targetNamespace = "http://webservices/", className = "webservices.EnviarInformeAuditoriaResponse")
    public java.lang.String enviarInformeAuditoria(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "generarRespuesta", targetNamespace = "http://webservices/", className = "webservices.GenerarRespuesta")
    @WebMethod
    @ResponseWrapper(localName = "generarRespuestaResponse", targetNamespace = "http://webservices/", className = "webservices.GenerarRespuestaResponse")
    public java.lang.String generarRespuesta(
        @WebParam(name = "arg0", targetNamespace = "")
        boolean arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
