
package uade.fain.ia.tpo.interfaces.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2014-11-10T22:23:15.957-03:00
 * Generated source version: 2.7.7.redhat-1
 */

@WebFault(name = "Exception", targetNamespace = "http://soap.interfaces.tpo.ia.fain.uade/")
public class Exception_Exception extends java.lang.Exception {
    
    private uade.fain.ia.tpo.interfaces.soap.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, uade.fain.ia.tpo.interfaces.soap.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, uade.fain.ia.tpo.interfaces.soap.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public uade.fain.ia.tpo.interfaces.soap.Exception getFaultInfo() {
        return this.exception;
    }
}
