
package uade.fain.ia.tpo.interfaces.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2014-11-08T16:36:54.653-03:00
 * Generated source version: 2.7.7.redhat-1
 */

@WebFault(name = "Exception", targetNamespace = "http://soap.interfaces.tpo.ia.fain.uade/")
public class ExceptionException extends java.lang.Exception {
    
    private uade.fain.ia.tpo.interfaces.soap.Exception exception;

    public ExceptionException() {
        super();
    }
    
    public ExceptionException(String message) {
        super(message);
    }
    
    public ExceptionException(String message, Throwable cause) {
        super(message, cause);
    }

    public ExceptionException(String message, uade.fain.ia.tpo.interfaces.soap.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public ExceptionException(String message, uade.fain.ia.tpo.interfaces.soap.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public uade.fain.ia.tpo.interfaces.soap.Exception getFaultInfo() {
        return this.exception;
    }
}
