
package uade.fain.ia.tpo.interfaces.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2014-11-08T16:36:54.449-03:00
 * Generated source version: 2.7.7.redhat-1
 */

@WebFault(name = "OrdenDespachoYaExisteException", targetNamespace = "http://soap.interfaces.tpo.ia.fain.uade/")
public class OrdenDespachoYaExisteExceptionException extends java.lang.Exception {
    
    private uade.fain.ia.tpo.interfaces.soap.OrdenDespachoYaExisteException ordenDespachoYaExisteException;

    public OrdenDespachoYaExisteExceptionException() {
        super();
    }
    
    public OrdenDespachoYaExisteExceptionException(String message) {
        super(message);
    }
    
    public OrdenDespachoYaExisteExceptionException(String message, Throwable cause) {
        super(message, cause);
    }

    public OrdenDespachoYaExisteExceptionException(String message, uade.fain.ia.tpo.interfaces.soap.OrdenDespachoYaExisteException ordenDespachoYaExisteException) {
        super(message);
        this.ordenDespachoYaExisteException = ordenDespachoYaExisteException;
    }

    public OrdenDespachoYaExisteExceptionException(String message, uade.fain.ia.tpo.interfaces.soap.OrdenDespachoYaExisteException ordenDespachoYaExisteException, Throwable cause) {
        super(message, cause);
        this.ordenDespachoYaExisteException = ordenDespachoYaExisteException;
    }

    public uade.fain.ia.tpo.interfaces.soap.OrdenDespachoYaExisteException getFaultInfo() {
        return this.ordenDespachoYaExisteException;
    }
}
